server:
  # Which hostname to listen for incoming connections.
  #
  # Examples:
  #
  # To listen on local connections over IPv6 only:
  # - '[::1]'
  #
  # To listen on local connections over IPv4 only:
  # - '127.0.0.1'
  #
  # To listen to the IP addresses a domain resolves to:
  # - some.domain.net
  hostname: ''
  port: 8085

  debug: false

  # Serious-mode makes some messages more formal and business-friendly.
  serious: false

  # Modules to be loaded by the bot. Each module provides a set of commands for
  # the bot. To enable/disable a module, simply uncomment/comment the lines
  # below.
  modules:
    # Provides the essential functionality of the bot.
    - core
    # Provides integration with the Phabricator extension.
    # - extension
    # Provides commands useful for the development of Phabulous.
    # - dev
slack:
  token: YOUR_TOKEN_HERE
  username: phabulous

  # Use this flag to enable/disable the Slack connector.
  enable: true

  # If you would like the bot messages to be consistent, you can make it use
  # the same account for posting both feed messages and real time commands.
  #
  # This does have the side effect that the bot will have to be manually
  # invited to every channel you would like it to participate in.
  #
  # When set to false, the bot will post like any other integration (like
  # webhooks). This allows it to post on almost any channel without having to
  # be invited.
  as-user: true
irc:
  # Use this flag to enable/disable the IRC connector.
  enable: false

  nick: phabulous

  hostname: some.irc.server
  #password: somethingsecret
  port: 6667
  tls: true
conduit:
  api: https://phabricator.replace.me

  # For token-based auth, use the following key:
  token: YOUR_TOKEN_HERE

  # For certificate-based auth, use the following keys:
  #user: etcinit
  #cert: ''
channels:
  # The feed channel is where Phabulous will post every feed event to this
  # channel. Leave it blank to disable this feature.
  feed: '#phabricator'

  # You can map repositories to a channel. This will send feed events regarding
  # commits and revisions to the specified channel.
  repositories:
    CALLSIGN: '#channel'
    OTHERCALLSIGN: '#otherchannel'

  # You can map projects to a channel. This will send feed events regarding
  # tasks to the specified channel.
  projects:
    10: '#anotherchannel'
core:
  summon:
    # Expand projects while summoning by listing all their members.
    #
    # Some organizations might have very large projects, making this very
    # impractical. Therefore, it can be disabled below.
    expandProjects: true

    # By default, Phabulous excludes the requestor's username. You can disable
    # this behavior below.
    includeSelf: false
misc:
  ignore-ca: false
